set (MAIN_HEADERS
	"${${CMAKE_PROJECT_NAME}_SOURCE_DIR}/include/AppDelegate.h")
source_group ("${CMAKE_PROJECT_NAME}\\Main" FILES ${MAIN_HEADERS})

set (${CMAKE_PROJECT_NAME}_SOURCES ${MAIN_HEADERS} ${${CMAKE_PROJECT_NAME}_SOURCES})
