set (MAIN_RESOURCES
	"${${CMAKE_PROJECT_NAME}_SOURCE_DIR}/res/LaunchScreen.storyboard")

source_group ("${CMAKE_PROJECT_NAME}\\Resources" FILES ${MAIN_RESOURCES})

set (${CMAKE_PROJECT_NAME}_SOURCES ${MAIN_RESOURCES} ${${CMAKE_PROJECT_NAME}_SOURCES})
