set (MAIN_SOURCES
	"${${CMAKE_PROJECT_NAME}_SOURCE_DIR}/src/main.m"
	"${${CMAKE_PROJECT_NAME}_SOURCE_DIR}/src/AppDelegate.m")
source_group ("${CMAKE_PROJECT_NAME}\\Main" FILES ${MAIN_SOURCES})

set (${CMAKE_PROJECT_NAME}_SOURCES ${MAIN_SOURCES} ${${CMAKE_PROJECT_NAME}_SOURCES})
